# Generated by Django 3.1.2 on 2020-11-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('Image', models.ImageField(null=True, upload_to='insumos')),
                ('Description', models.TextField()),
                ('Stock', models.IntegerField()),
            ],
        ),
    ]
